list:
    just --list

all:
    just miri
    just cov

kani *args:
    cargo kani -Z loop-contracts -Z stubbing -Z function-contracts \
        --no-default-checks --no-memory-safety-checks \
        --no-overflow-checks --no-undefined-function-checks \
        --no-unwinding-checks {{ args }}

miri *args:
    #!/usr/bin/env -S bash -euo pipefail
    source ../miri-env.sh
    cargo miri nextest run --target-dir target/miri -p trame {{ args }}

cov *args:
    #!/usr/bin/env -S bash -euo pipefail
    source ../miri-env.sh
    cargo llvm-cov nextest --ignore-filename-regex '/facet-(core|macro|macros|reflect)' {{ args }}
