list:
    just --list

all:
    just kani
    just test

sote *args:
    soteria-rust cargo . --kani --summary {{ args }}

kani *args:
    #!/usr/bin/env bash
    # cargo kani {{ args }}
    cat <<EOF
    Use "just sote" instead, which requires switching to the right opal env
    For me that's:
    eval \$(opam env --switch=/Users/amos/bearcove/soteria --set-switch)
    EOF
    exit 1

test *args:
    cargo test -p trame-formal {{ args }}
