list:
    just --list

all:
    just kani
    just test

sote *args:
    soteria-rust cargo . --kani --summary {{ args }}

kani *args:
    cargo kani {{ args }}

test *args:
    cargo test -p trame-formal {{ args }}
